[tool.poetry]
name = "ksenia20-09-24"
version = "0.1.0"
description = ""
authors = ["Artyom <kostyuchenko.work@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
